repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
    # Ensure that uv.lock is up to date
    -   id: uv-lock
    # Export dependencies to requirements.txt
    -  id: uv-export